### ISSUE TITLE
[GoC]First Attack

### ISSUE THREAD

**Issue by TheotimeBalaguer** [AkanshDivker/polyengine#6]
- **Version**: Last commit : 146c9f8b60e61a7a12a27ca090acbf5a3c22d305

- **Environment**: tested on Ubuntu 18.04.3 LTS but true for all environments

- **Location**: /polyengine/util/encryption.py : 

```
15	    def __init__(self, key: str):
16	        self.key = md5(key.encode('utf-8')).digest()
```

- **Type** : Insecure hash algorithm

- **Explanation**: Since several years now, md5 is considered a weak, insecure algorithm, and it should not be used. The main reason is that md5 is a General Purpose (fast) Hash function, providing the attacker the possibility to test billions of keys every second, enabling brute-force attacks. 

But there is more, this type of algorithm can be broken by the "chosen prefix attacks", and even if the process is sofisticated, it can still be implemented, like in [this](https://www.win.tue.nl/hashclash/rogue-ca/) paper, or [here](https://www.win.tue.nl/hashclash/TargetCollidingCertificates/).

> "Collision" in MD5 allow construction of different messages with the same MD5 hash.

**Comment by AkanshDivker** [comment]
### **Patch Report**

- Commit ID: 146c9f8 + 229a810

- Cause of vulnerability: Weak hashing algorithm.

- Explanation: Hashing algorithm for key replaced to a more secure one, SHA256.
